name: uniuni
description: "2024 2학기 flutter."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Note: assets
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^1.2.3

  # Note: core
  easy_extension:
    git:
      url: https://github.com/scadasystems/Easy-Extension.git
  flex_color_scheme: ^7.3.1
  file_picker: ^8.1.4
  go_router: ^14.6.0
  http:
  shared_preferences: ^2.3.3
  http_parser:
  mime:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
